### ISSUE TITLE
Generating data meets error "ValueError: sequence must not be empty"

### ISSUE THREAD

**Issue by island255** [HKUST-KnowComp/NeuralSubgraphCounting#6]
I have created a conda environment using python3.7 and installed all the required packages in the requirements.txt. Then I try to use the following instruction to create a dataset.

`cd generator`
`python run.py`

However, it first raises an error that "ModuleNotFoundError: No module named 'igraph'.

Then I installed the igraph package using "pip install python-igraph", but another error was raised.

```
python run.py
patterns_id P_N3_E2_NL2_EL2
patterns_id P_N3_E4_NL2_EL2
patterns_id P_N3_E4_NL2_EL4
patterns_id P_N4_E4_NL2_EL2
patterns_id P_N4_E4_NL2_EL4
patterns_id P_N4_E4_NL4_EL2
patterns_id P_N4_E4_NL4_EL4
7 patterns generation finished!
  0%|                                                                                                                                                              | 0/112 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/jiaang/.conda/envs/subgraph/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "run.py", line 97, in generate_graphs
    alpha, max_pattern_counts=max_pattern_counts, max_subgraph=max_subgraph, return_subisomorphisms=True)
  File "/data2/jiaang/github/NeuralSubgraphCounting/generator/graph_generator.py", line 484, in generate
    self.update_subgraphs(subgraphs, graph_edge_label_mapping)
  File "/data2/jiaang/github/NeuralSubgraphCounting/generator/graph_generator.py", line 331, in update_subgraphs
    subgraph.es["label"] = new_edge_labels_in_subgraphs[sg]
ValueError: sequence must not be empty
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 204, in <module>
    x.get()
  File "/home/jiaang/.conda/envs/subgraph/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: sequence must not be empty
```
Could you help me solve this issue?

**Comment by seanliu96** [comment]
Could you please try to use single-thread generation instead of multi-threads? It would be easier to debug. From the current error message, the variable new_edge_labels_in_subgraphs[sg] is empty, but the subgraph demands a non-empty variable.

**Comment by seanliu96** [comment]
One possible reason is the latest python-igraph does not support graphs with multi-edges. Please try python-igraph==0.9.11 .

**Comment by island255** [comment]
I try to reinstall python-igraph with version 0.9.11 and run without error. 

Thank you very much!

**Comment by seanliu96** [comment]
Cheers!
