### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'device'  Process finished with exit code 1

### ISSUE THREAD

**Issue by Faker0715** [HKUST-KnowComp/NeuralSubgraphCounting#7]
python train_mutag.py --model RGIN --predict_net SumPredictNet \
    --gpu_id 0 --batch_size 64 \
    --max_npv 4 --max_npe 3 --max_npvl 2 --max_npel 2 \
    --max_ngv 28 --max_nge 66 --max_ngvl 7 --max_ngel 4 \
    --pattern_dir ../data/MUTAG/patterns \
    --graph_dir ../data/MUTAG/raw \
    --metadata_dir ../data/MUTAG/metadata \
    --save_data_dir ../data/MUTAG/RGIN-SumPredictNet-0.4 \
    --save_model_dir ../dumps/MUTAG \
    --train_ratio 0.4

problem:
![image](https://user-images.githubusercontent.com/36560441/202229634-66c91543-b5ea-4ac2-939f-81bc01c5ebd1.png)

Traceback (most recent call last):
  File "/home/faker/Desktop/code/NeuralSubgraphCounting-master/src/train_mutag.py", line 249, in <module>
    dataset = GraphAdjDataset(x)
  File "/home/faker/Desktop/code/NeuralSubgraphCounting-master/src/dataset.py", line 218, in __init__
    self.data = GraphAdjDataset.preprocess_batch(data, use_tqdm=True)
  File "/home/faker/Desktop/code/NeuralSubgraphCounting-master/src/dataset.py", line 319, in preprocess_batch
    d.append(GraphAdjDataset.preprocess(x))
  File "/home/faker/Desktop/code/NeuralSubgraphCounting-master/src/dataset.py", line 291, in preprocess
    pattern_dglgraph.ndata["indeg"] = np.array(pattern.indegree(), dtype=np.float32)
  File "/home/faker/.conda/envs/ISONET/lib/python3.9/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/faker/.conda/envs/ISONET/lib/python3.9/site-packages/dgl/heterograph.py", line 4112, in _set_n_repr
    if F.context(val) != self.device:
  File "/home/faker/.conda/envs/ISONET/lib/python3.9/site-packages/dgl/backend/pytorch/tensor.py", line 82, in context
    return input.device
AttributeError: 'numpy.ndarray' object has no attribute 'device'

Process finished with exit code 1

**Comment by Faker0715** [comment]
i think i need to install dgl == 0.4.3post2. wait me close
